name: Rustfmt and clippy check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  rustfmt_clippy:
    strategy:
      fail-fast: true

    name: Rustfmt and clippy check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy
